input:
  ip: "192.168.1.99"
  port: 50000
output:
  ip: "192.168.1.20"
  port: 503
broker:
  # server: "test.mosquitto.org"
  # server: "localhost"
  server: "host.docker.internal"
  port: 1883
  topic: "test/message"
  message: "Hello, world."
