# Data Diode Settings
input:
  ip: "192.168.1.99"
  port: 50000
  timeout: 60 # seconds
output:
  ip: "192.168.1.20"
  port: 503
  tls: false
broker:
  server: "test.mosquitto.org"
  port: 1883
  topic: "diode/telemetry"
  message: "Hello, world."
  index: 42
  checksum: ["MD5", "SHA-1", "SHA-256"]
