# Project Settings
diode:
  input:
    ip: "localhost"
    port: 49152
    timeout: 60 # seconds
  output:
    ip: "localhost"
    port: 13337
    tls: false
mqtt:
  inside:
    server: "localhost"
    port: 1883
    topic: "#"
  outside:
    server: "localhost"
    port: 1883
    prefix: "diode" # Avoid namespace collisions
